name: crop_monitoring_system
description: A comprehensive Flutter application for monitoring crop health and environmental conditions in real-time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'  # Using latest stable SDK version

dependencies:
  flutter:
    sdk: flutter
    
  # State Management
  get: ^4.6.6

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1

  # Charts and Data Visualization
  fl_chart: ^0.66.1
  
  # Networking and Data
  http: ^1.2.2
  mysql1: ^0.20.0
  
  # Local Storage and Preferences
  shared_preferences: ^2.2.2
  
  # Date and Time Formatting
  intl: ^0.19.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

          